import { button, image, joinText, section, text, type SectionDef } from "../seed-helpers";

const ARTICLE_IMG: Record<string, string> = {
  understandingYourLiver:
    "https://lh3.googleusercontent.com/aida-public/AB6AXuAVVZygLn3qRswzY1427qBP2JA6H7Hv7DNajCVKPjacNxB5TelKmu22iGUXNdqafwG09SpTBN21qtxVECPH7bjXRDatKix-e2nmRvLHenH2wWTTfa4TDen5rkmVKGGbUa9tCyln1pdSMTWZGgr2tylKECwjXC9NTqSKBFAqy2YhQeA_X04sdhYuFsWa5DZjfKetLA1zD8HRnabDI67vWZR2lnzMCBvp_RjrAuRG8-Xifp5B8Im1y7Xz",
  biliaryTreeMapping:
    "https://lh3.googleusercontent.com/aida-public/AB6AXuBm3XTmDg8IA2CfLP4is0IFpsJFTZ3ObC4bJV5otfDKgpIIrzKbWQWtsu8FO7iT-Yz9lL6NMf9u95gkCfvyeOsAlqv89dZpqhJ7BuLej9b-1TJvGTYrOWG8U3L3h57NAl2MnS2zWDlwyYgz1rHDrATxuRX1ccE3_KdX7IjF8oeQiiW1rrcB2FquepQbrjAmr7dti9jmJaRD4Bx6K-gs-Lqd_QTSbA8J0pnneZJ77N8NFL2YK9TP4cwX",
  roadToRecovery:
    "https://lh3.googleusercontent.com/aida-public/AB6AXuAjvBGwKa3vRwBMyX_OL4k1GtG_hPfF2fmV9yKVDsA9onRw81cQ9l9yGM-YDzoXVjfErooVrILD2kDvCi8rtCcWgZ8cqqcci4bG3rcQ2c1HDaVwL9mJ89Z8-yJH6LnFf766SWRdLoQAfHXmBFb1MC_zInQZzVkoFxu15PsnOXsaq5d-odCWrh4XsNY9BDDxwcsKjZUjF1NvO_g8alQOGqYDASPSYKyjvyjL-h8-7hn5_-2bCkKCzrYP",
  roboticAssistance:
    "https://lh3.googleusercontent.com/aida-public/AB6AXuBnTI3dIS82iU3FvcvwDJjUNXZ6LYba6OFgMREpvPd9qAUjpWM8BSbCmh51Qko-EBWC3iS01yb8fTUP4rZnvI5r8ESpsB0ge5h5T0iBgl9_aahdAzfLfUG4iU5NZLHKNsfUQmKHeQ4gXaQdH5A6_nPyfUaUDWG75C3gcwZBN0iz0zDL6snmOTOyIG1cn90b-TbC7WqJ7X8C6OV-hgyBE4woo4yn4rSMvxq_r2ZRHH4LNE-R3JHJX4dT",
  advancedSterilization:
    "https://lh3.googleusercontent.com/aida-public/AB6AXuA7aSa6ddeBmLAcZ6QK0Pw0-715_ZAp7Y7gaPJ5xKC9hlkMLNSrmU_V-oE_g9JeN7BLBAgB6_JS--iIFPm8fYQs5upncqfTO-fxzIp7mkY-tBvI3_S390xQSG5weOFyHoqh1GCIR7lNzHJs1_3nZbDvV6BghWwN1nmeBNTiYhhaVbCCE_VzZf44Ok2RsbqzYUFxYc1C6L7ekahWVDlFCurJPyq3wmfqocrSzWYT1lkUmLTseHK-_mdl",
  scientificConferences:
    "https://lh3.googleusercontent.com/aida-public/AB6AXuCILOmYD4hlsRfuFPxZ76fhp4hp_O4jalWck8pX8u_bDQjpjuVRLCxJyWa_3XLG_SWZ3KR1KTmh781K03zOvGLLOVnd2vPzetxHHxoyFLAzsq5QiPjEtNcIpqzgir-k2xajMOAHPbLdyTpX3jxsSO-HJ7vY_NaHANEFJvJKtZhHlRm8xK99V6caZTTrP8NRDg4Wd_sELGYH7g_JZUYEy5n-pYYPMe2VJA1WkcGliWGWpnnXWOy-dtNb",
  multidisciplinaryCare:
    "https://lh3.googleusercontent.com/aida-public/AB6AXuB0Nh8MrVcViOUgldhb86RIYVFSiVkaL2srthrPYHZWmhl1gjjfDiNTBl7Jsc1lGG2gX7spvOcVIlYoEJYhIH9QWtHAdagzI9cwkhtn7UVPeoSOZFc9uogbfwshYGZFBj7hwWozTE0pSFFdwhzTb7v5daDVzAHrGXlTAY4sesguH0K7lhl6NVIin2OchdiJBtkzB_sC-Q-4yTXRrqnG8K7Hq4flf_CO_DzoxgDxr2vg43Tnxhdz9DE1",
  futureOfHepatology:
    "https://lh3.googleusercontent.com/aida-public/AB6AXuAE4vIseia-EYulnu-dDGDb9RzxgV-4DUqZh_69wCKTi2kofrPP6eQq7wnQQM0CUdONfXn6mumyMQXWfUlbCUBAaI2BoYlHmhRP0IFZPpf4jlesqggbH6hSakYftwp3puvyjU7ojlbssxp-m8InTw8EHyu7WHyk6dWTFa83xTAPDDQI2sNn1i40fSAX--yEHlgqcR1KYHSEeKJhyNw_7BEUv2GWUEgYiIn4QCw6MSypXFPAFEPsUmsg",
};

// Fresh translations: these alts existed only as literal English strings
// baked into the JSX, never as translation keys.
const heroBgAlt = {
  en: "Abstract representation of medical knowledge and research, featuring soft teal glowing lines intersecting like a digital neural network over a bright, clinical white background.",
  ar: "تمثيل تجريدي للمعرفة والبحث الطبي، يظهر خطوطاً متوهجة بلون تركوازي ناعم تتقاطع كأنها شبكة عصبية رقمية فوق خلفية بيضاء سريرية مشرقة.",
  fr: "Représentation abstraite du savoir et de la recherche médicale, avec de douces lignes lumineuses turquoise s'entrecroisant comme un réseau neuronal numérique sur un fond blanc clinique lumineux.",
};
const featuredImageAlt = {
  en: "Cinematic 3D medical visual of a human liver",
  ar: "تصور طبي سينمائي ثلاثي الأبعاد للكبد البشري",
  fr: "Visuel médical 3D cinématographique d'un foie humain",
};

// Fresh, fully-authored article bodies (EN/AR/FR) - these are the CMS's
// real values, written for this migration since only a tag+title existed
// before. Each is genuine, substantive copy (not lorem ipsum), editable
// per-article afterwards from /admin/pages/articles.
const featuredBody = {
  en: "Liver transplantation has always demanded absolute precision, but the margin for error shrinks even further in complex cases involving unusual vascular anatomy or diseased tissue close to critical structures. Over the past decade, high-fidelity 3D modeling has moved from a research curiosity into a genuine surgical planning tool, letting our team walk through a patient's exact anatomy before ever making an incision.\n\nBy converting standard CT and MRI scans into detailed, rotatable 3D reconstructions, we can identify the safest resection planes, anticipate variant blood vessels, and rehearse the most delicate steps of a transplant days in advance. What used to rely on two-dimensional imaging and years of accumulated intuition can now be visualized directly, reducing operative time and, more importantly, reducing risk.\n\nWe are now exploring how liquid-glass simulation techniques, borrowed from computational fluid dynamics, can model blood flow through a reconstructed liver in real time. Combined with 3D modeling, this gives us an unprecedented preview of how a graft will perform once connected. It is a clear example of how surgical precision and patient safety improve when technology and experience work together.",
  ar: "تتطلب زراعة الكبد دقة مطلقة دائماً، إلا أن هامش الخطأ يضيق أكثر في الحالات المعقدة التي تنطوي على تشريح وعائي غير معتاد أو أنسجة مريضة قريبة من تراكيب حيوية. على مدى العقد الماضي، تحول النمذجة ثلاثية الأبعاد عالية الدقة من مجرد أداة بحثية إلى وسيلة حقيقية للتخطيط الجراحي، مما يتيح لفريقنا استعراض التشريح الدقيق للمريض قبل إجراء أي شق جراحي.\n\nمن خلال تحويل صور الأشعة المقطعية والرنين المغناطيسي القياسية إلى نماذج ثلاثية الأبعاد تفصيلية وقابلة للتدوير، يمكننا تحديد أكثر مستويات الاستئصال أماناً، وتوقع الأوعية الدموية غير النمطية، والتدرب على أدق خطوات عملية الزراعة قبل أيام من إجرائها. وما كان يعتمد سابقاً على التصوير ثنائي الأبعاد وسنوات من الخبرة المتراكمة، أصبح الآن مرئياً بشكل مباشر، مما يقلل من وقت الجراحة، والأهم من ذلك، يقلل من المخاطر.\n\nنستكشف حالياً كيف يمكن لتقنيات محاكاة \"الزجاج السائل\"، المستعارة من ديناميكا الموائع الحاسوبية، أن تحاكي تدفق الدم عبر الكبد المعاد بناؤه في الوقت الفعلي. وبدمج هذه التقنية مع النمذجة ثلاثية الأبعاد، نحصل على معاينة غير مسبوقة لكيفية أداء الطعم بعد توصيله. وهذا مثال واضح على كيف تتحسن الدقة الجراحية وسلامة المريض عندما تتضافر التكنولوجيا مع الخبرة.",
  fr: "La transplantation hépatique a toujours exigé une précision absolue, mais la marge d'erreur se réduit encore davantage dans les cas complexes impliquant une anatomie vasculaire inhabituelle ou des tissus malades proches de structures critiques. Au cours de la dernière décennie, la modélisation 3D haute fidélité est passée d'une curiosité de recherche à un véritable outil de planification chirurgicale, permettant à notre équipe d'explorer l'anatomie exacte du patient avant la moindre incision.\n\nEn convertissant les scanners CT et IRM standards en reconstructions 3D détaillées et pivotantes, nous pouvons identifier les plans de résection les plus sûrs, anticiper les vaisseaux sanguins variants et répéter les étapes les plus délicates d'une transplantation plusieurs jours à l'avance. Ce qui reposait autrefois sur l'imagerie bidimensionnelle et des années d'intuition accumulée peut désormais être visualisé directement, réduisant le temps opératoire et, plus important encore, le risque.\n\nNous explorons désormais comment les techniques de simulation « verre liquide », empruntées à la dynamique des fluides numérique, peuvent modéliser en temps réel la circulation sanguine dans un foie reconstruit. Combinée à la modélisation 3D, cette approche offre un aperçu sans précédent du comportement d'un greffon une fois connecté. C'est un exemple clair de la façon dont la précision chirurgicale et la sécurité des patients s'améliorent lorsque la technologie et l'expérience travaillent de concert.",
};

const ARTICLE_BODIES: Record<string, { en: string; ar: string; fr: string }> = {
  understandingYourLiver: {
    en: "The liver is one of the few organs in the body capable of regenerating itself, which is precisely what makes procedures like partial resection and living-donor transplantation possible. It filters toxins from the blood, produces essential proteins, stores energy, and helps regulate digestion — all functions that quietly continue even when the organ is under significant stress.\n\nMany liver conditions progress silently for years before symptoms appear, which is why routine blood work and imaging matter even when you feel well. Fatigue, unexplained bruising, swelling in the abdomen or legs, and yellowing of the skin or eyes are signs worth discussing with a specialist rather than waiting out.\n\nUnderstanding your own liver health starts with knowing your risk factors — family history, viral hepatitis exposure, alcohol use, and metabolic conditions like diabetes all play a role. A clear conversation with your doctor about these factors is the first step toward catching problems early, when treatment options are broadest.",
    ar: "الكبد هو أحد الأعضاء القليلة في الجسم القادرة على تجديد نفسها، وهذا بالضبط ما يجعل إجراءات مثل الاستئصال الجزئي وزراعة الكبد من متبرع حي ممكنة. فهو يقوم بتنقية الدم من السموم، وإنتاج البروتينات الأساسية، وتخزين الطاقة، والمساعدة في تنظيم عملية الهضم - وجميعها وظائف تستمر بهدوء حتى عندما يكون العضو تحت ضغط كبير.\n\nتتطور العديد من أمراض الكبد بصمت لسنوات قبل ظهور الأعراض، ولهذا السبب تعتبر فحوصات الدم والتصوير الروتينية مهمة حتى عندما تشعر أنك بخير. التعب، والكدمات غير المبررة، وتورم البطن أو الساقين، واصفرار الجلد أو العينين، كلها علامات تستحق مناقشتها مع أخصائي بدلاً من الانتظار.\n\nيبدأ فهم صحة كبدك من معرفة عوامل الخطر الخاصة بك - التاريخ العائلي، والتعرض لالتهاب الكبد الفيروسي، وتناول الكحول، والحالات الأيضية مثل السكري، كلها عوامل مؤثرة. إن إجراء حوار واضح مع طبيبك حول هذه العوامل هو الخطوة الأولى نحو اكتشاف المشكلات مبكراً، عندما تكون خيارات العلاج في أوسع نطاقاتها.",
    fr: "Le foie est l'un des rares organes du corps capable de se régénérer, ce qui rend précisément possibles des interventions comme la résection partielle et la transplantation à partir d'un donneur vivant. Il filtre les toxines du sang, produit des protéines essentielles, stocke l'énergie et aide à réguler la digestion — autant de fonctions qui se poursuivent discrètement même lorsque l'organe est soumis à un stress important.\n\nDe nombreuses maladies du foie évoluent silencieusement pendant des années avant l'apparition de symptômes, c'est pourquoi les bilans sanguins et l'imagerie de routine sont importants même lorsque vous vous sentez bien. La fatigue, des ecchymoses inexpliquées, un gonflement de l'abdomen ou des jambes, et un jaunissement de la peau ou des yeux sont des signes qui méritent d'être évoqués avec un spécialiste plutôt qu'ignorés.\n\nComprendre la santé de son foie commence par connaître ses facteurs de risque — antécédents familiaux, exposition à l'hépatite virale, consommation d'alcool et affections métaboliques comme le diabète jouent tous un rôle. Une discussion claire avec votre médecin sur ces facteurs est la première étape pour détecter les problèmes tôt, lorsque les options de traitement sont les plus larges.",
  },
  biliaryTreeMapping: {
    en: "The biliary tree — the network of ducts that carries bile from the liver to the small intestine — is notoriously variable from one patient to the next. No two patients share exactly the same branching pattern, which is why careful mapping before any hepatobiliary surgery is non-negotiable rather than optional.\n\nModern imaging techniques, including MRCP (magnetic resonance cholangiopancreatography) and intraoperative cholangiography, let us trace each duct's course with a level of detail that simply wasn't available a generation ago. This matters most in procedures like living-donor liver resection, where preserving biliary drainage for both the donor and recipient is critical to a safe recovery.\n\nPrecision here is not about performing a more impressive operation — it is about avoiding the complications, like bile leaks or strictures, that turn a successful resection into a difficult recovery. Every extra minute spent mapping the biliary anatomy before the first incision pays for itself many times over in the weeks that follow.",
    ar: "تُعرف الشجرة الصفراوية - شبكة القنوات التي تنقل الصفراء من الكبد إلى الأمعاء الدقيقة - بتنوعها الكبير من مريض لآخر. فلا يوجد مريضان يتشاركان نفس نمط التفرع بالضبط، ولهذا يُعد رسم خريطة دقيقة لها قبل أي جراحة كبدية صفراوية أمراً ضرورياً وليس اختيارياً.\n\nتتيح لنا تقنيات التصوير الحديثة، بما في ذلك تصوير القنوات الصفراوية والبنكرياس بالرنين المغناطيسي والتصوير الصفراوي أثناء العملية، تتبع مسار كل قناة بمستوى من التفصيل لم يكن متاحاً قبل جيل واحد فقط. وهذا الأمر بالغ الأهمية بشكل خاص في إجراءات مثل استئصال جزء من كبد متبرع حي، حيث يُعد الحفاظ على التصريف الصفراوي لكل من المتبرع والمتلقي أمراً حاسماً لتعافٍ آمن.\n\nالدقة هنا لا تتعلق بإجراء عملية أكثر إبهاراً، بل تتعلق بتجنب المضاعفات، مثل تسرب الصفراء أو التضيقات، التي تحول عملية استئصال ناجحة إلى تعافٍ صعب. فكل دقيقة إضافية تُقضى في رسم خريطة التشريح الصفراوي قبل الشق الأول تعود بفائدة مضاعفة في الأسابيع التالية.",
    fr: "L'arbre biliaire — le réseau de canaux qui achemine la bile du foie vers l'intestin grêle — est réputé pour sa grande variabilité d'un patient à l'autre. Aucun patient ne partage exactement le même schéma de ramification, c'est pourquoi une cartographie minutieuse avant toute chirurgie hépatobiliaire n'est pas optionnelle mais indispensable.\n\nLes techniques d'imagerie modernes, notamment la cholangio-pancréatographie par IRM (MRCP) et la cholangiographie peropératoire, nous permettent de suivre le trajet de chaque canal avec un niveau de détail tout simplement inaccessible il y a une génération. Cela compte particulièrement dans des interventions comme la résection hépatique chez un donneur vivant, où préserver le drainage biliaire du donneur et du receveur est essentiel à une récupération sûre.\n\nLa précision ici ne vise pas à réaliser une opération plus impressionnante — elle vise à éviter les complications, comme les fuites biliaires ou les sténoses, qui transforment une résection réussie en une convalescence difficile. Chaque minute supplémentaire consacrée à cartographier l'anatomie biliaire avant la première incision se rentabilise largement dans les semaines qui suivent.",
  },
  roadToRecovery: {
    en: "The first weeks after a liver transplant are focused on stabilization: adjusting immunosuppressive medication, watching for early signs of rejection, and helping the new organ settle into its role. Most patients are surprised by how quickly energy returns once the transplanted liver begins functioning normally — often faster than the fatigue that built up during months of illness beforehand.\n\nRecovery is not a straight line. Regular blood tests, occasional biopsies, and close communication with your transplant team are how we catch small issues before they become large ones. Diet, gentle exercise, and strict adherence to medication schedules matter just as much as anything done in the operating room.\n\nBeyond the physical recovery, many patients describe a genuine shift in perspective — a return to travel, work, and time with family that had felt out of reach during the years of declining liver function. The goal of transplantation was never just survival; it was giving patients their lives back.",
    ar: "تركز الأسابيع الأولى بعد زراعة الكبد على تحقيق الاستقرار: ضبط أدوية تثبيط المناعة، ومراقبة العلامات المبكرة للرفض، ومساعدة العضو الجديد على التأقلم مع دوره. يتفاجأ معظم المرضى بسرعة عودة النشاط بمجرد أن يبدأ الكبد المزروع بالعمل بشكل طبيعي - وغالباً ما تكون أسرع من التعب الذي تراكم خلال أشهر المرض السابقة.\n\nالتعافي ليس خطاً مستقيماً. فحوصات الدم المنتظمة، والخزعات العرضية، والتواصل الوثيق مع فريق الزراعة، هي الوسائل التي نستخدمها لاكتشاف المشكلات الصغيرة قبل أن تتفاقم. النظام الغذائي، والتمارين الخفيفة، والالتزام الصارم بمواعيد الأدوية، لها نفس القدر من الأهمية مثل أي شيء يتم داخل غرفة العمليات.\n\nبعيداً عن التعافي الجسدي، يصف العديد من المرضى تحولاً حقيقياً في نظرتهم للحياة - عودة إلى السفر، والعمل، وقضاء الوقت مع العائلة، وهي أمور بدت بعيدة المنال خلال سنوات تدهور وظائف الكبد. لم يكن هدف الزراعة يوماً مجرد النجاة، بل إعادة الحياة إلى المرضى.",
    fr: "Les premières semaines suivant une transplantation hépatique sont consacrées à la stabilisation : ajustement des médicaments immunosuppresseurs, surveillance des premiers signes de rejet, et aide au nouvel organe pour s'intégrer à son rôle. La plupart des patients sont surpris de la rapidité avec laquelle l'énergie revient une fois que le foie transplanté commence à fonctionner normalement — souvent plus vite que ne s'était installée la fatigue accumulée pendant les mois de maladie précédents.\n\nLa guérison n'est pas linéaire. Des analyses sanguines régulières, des biopsies occasionnelles et une communication étroite avec votre équipe de transplantation permettent de repérer les petits problèmes avant qu'ils ne s'aggravent. L'alimentation, une activité physique douce et le strict respect des horaires de médication comptent tout autant que ce qui se passe au bloc opératoire.\n\nAu-delà de la récupération physique, de nombreux patients décrivent un véritable changement de perspective — un retour aux voyages, au travail et au temps passé en famille qui semblait inaccessible pendant les années de déclin de la fonction hépatique. L'objectif de la transplantation n'a jamais été la simple survie ; c'était de redonner leur vie aux patients.",
  },
  roboticAssistance: {
    en: "Robotic platforms have changed what is technically possible in hepatobiliary surgery, offering a level of dexterity and visualization that the human hand and eye alone cannot match. Instruments with a full range of wrist motion can access and work within tight spaces around the liver hilum that would otherwise require a much larger incision.\n\nThe magnified, high-definition 3D view available through robotic systems lets the surgical team identify small vessels and bile ducts with far greater confidence, which translates directly into safer dissection around critical structures. For patients, this often means smaller incisions, less blood loss, and a faster return to normal activity.\n\nRobotic assistance does not replace surgical judgment — it extends it. The decisions about how to approach a tumor, protect a vessel, or reconstruct a duct are still made by an experienced surgeon; the robot simply gives that surgeon steadier hands and a clearer view to act on that judgment.",
    ar: "غيّرت المنصات الروبوتية ما هو ممكن تقنياً في جراحة الكبد والصفراء، حيث توفر مستوى من البراعة والرؤية لا يمكن للعين واليد البشرية وحدهما مضاهاته. تستطيع الأدوات ذات نطاق الحركة الكامل للمعصم الوصول إلى المساحات الضيقة حول سرة الكبد والعمل بداخلها، وهو ما كان سيتطلب شقاً جراحياً أكبر بكثير.\n\nتتيح الرؤية ثلاثية الأبعاد المكبرة وعالية الدقة المتوفرة عبر الأنظمة الروبوتية للفريق الجراحي تحديد الأوعية الدموية والقنوات الصفراوية الصغيرة بثقة أكبر بكثير، وهو ما يُترجم مباشرة إلى تشريح أكثر أماناً حول التراكيب الحيوية. وبالنسبة للمرضى، غالباً ما يعني ذلك شقوقاً أصغر، وفقداناً أقل للدم، وعودة أسرع للأنشطة الطبيعية.\n\nالمساعدة الروبوتية لا تحل محل الحكم الجراحي - بل تعززه. فالقرارات المتعلقة بكيفية التعامل مع ورم، أو حماية وعاء دموي، أو إعادة بناء قناة، لا تزال تُتخذ من قبل جراح ذي خبرة؛ والروبوت ببساطة يمنح ذلك الجراح يداً أكثر ثباتاً ورؤية أوضح لتنفيذ ذلك الحكم.",
    fr: "Les plateformes robotiques ont transformé ce qui est techniquement possible en chirurgie hépatobiliaire, offrant un niveau de dextérité et de visualisation que la main et l'œil humains seuls ne peuvent égaler. Des instruments dotés d'une amplitude de mouvement du poignet complète permettent d'accéder à des espaces étroits autour du hile hépatique et d'y opérer, ce qui nécessiterait autrement une incision bien plus large.\n\nLa vue 3D grossie et haute définition offerte par les systèmes robotiques permet à l'équipe chirurgicale d'identifier les petits vaisseaux et canaux biliaires avec beaucoup plus de confiance, ce qui se traduit directement par une dissection plus sûre autour des structures critiques. Pour les patients, cela signifie souvent des incisions plus petites, moins de pertes sanguines et un retour plus rapide à une activité normale.\n\nL'assistance robotique ne remplace pas le jugement chirurgical — elle le prolonge. Les décisions sur la façon d'aborder une tumeur, de protéger un vaisseau ou de reconstruire un canal restent prises par un chirurgien expérimenté ; le robot lui offre simplement des mains plus stables et une vue plus claire pour agir sur ce jugement.",
  },
  advancedSterilization: {
    en: "Every instrument, surface, and airflow pathway in a hepatobiliary operating room goes through a sterilization protocol designed with one goal: eliminating the risk of infection for patients whose immune systems will soon be intentionally suppressed. This starts long before the patient enters the room.\n\nBeyond standard autoclaving, our facility uses layered protocols — from laminar airflow systems that continuously filter operating room air, to validated tracking of every surgical instrument from sterilization through use and back again. For transplant patients especially, this attention to detail continues well past the operating room, into how medications, catheters, and dressings are handled during recovery.\n\nPatients rarely see this side of their care, but it is one of the most consistent predictors of a smooth post-operative course. Safety in every step is not a slogan here — it is a checklist that gets followed the same way for every single patient, every single time.",
    ar: "تخضع كل أداة، وسطح، ومسار تدفق هواء في غرفة عمليات جراحة الكبد والصفراء لبروتوكول تعقيم مصمم لهدف واحد: القضاء على خطر العدوى لدى المرضى الذين ستُثبَّط أجهزتهم المناعية عمداً قريباً. وتبدأ هذه العملية قبل دخول المريض إلى الغرفة بوقت طويل.\n\nبالإضافة إلى التعقيم بالأوتوكلاف القياسي، تستخدم منشأتنا بروتوكولات متعددة الطبقات - من أنظمة تدفق الهواء الصفحي التي تُرشّح هواء غرفة العمليات باستمرار، إلى التتبع المعتمد لكل أداة جراحية من التعقيم وحتى الاستخدام والعودة مرة أخرى. وبالنسبة لمرضى الزراعة على وجه الخصوص، يستمر هذا الاهتمام بالتفاصيل إلى ما بعد غرفة العمليات، وصولاً إلى كيفية التعامل مع الأدوية والقسطرات والضمادات أثناء فترة التعافي.\n\nنادراً ما يرى المرضى هذا الجانب من رعايتهم، لكنه أحد أكثر العوامل ثباتاً في التنبؤ بمسار ما بعد الجراحة السلس. السلامة في كل خطوة ليست شعاراً هنا - بل قائمة تحقق تُتبع بنفس الطريقة مع كل مريض، في كل مرة.",
    fr: "Chaque instrument, surface et circuit d'air dans un bloc opératoire hépatobiliaire suit un protocole de stérilisation conçu dans un seul but : éliminer le risque d'infection pour des patients dont le système immunitaire sera bientôt intentionnellement affaibli. Cela commence bien avant que le patient n'entre dans la salle.\n\nAu-delà de l'autoclavage standard, notre établissement applique des protocoles superposés — des systèmes de flux d'air laminaire qui filtrent en continu l'air du bloc opératoire, jusqu'au suivi validé de chaque instrument chirurgical, de la stérilisation à l'utilisation puis au retour. Pour les patients transplantés en particulier, cette attention aux détails se poursuit bien au-delà du bloc opératoire, dans la manière dont les médicaments, cathéters et pansements sont gérés pendant la convalescence.\n\nLes patients voient rarement cet aspect de leurs soins, mais c'est l'un des indicateurs les plus fiables d'une évolution postopératoire sans accroc. La sécurité à chaque étape n'est pas un slogan ici — c'est une liste de contrôle suivie de la même façon pour chaque patient, à chaque fois.",
  },
  scientificConferences: {
    en: "Presenting at international conferences is not about prestige for its own sake — it is how surgical techniques get tested against a global audience of peers who will ask the hard questions your own team might not think to ask. Every case series and outcome data set shared on that stage comes back sharper for having been challenged.\n\nThese gatherings are also where the next generation of hepatobiliary innovation takes shape, long before it appears in journals or clinical guidelines. Conversations in conference hallways about a difficult case or a new imaging technique often lead directly to changes in how we approach patients back home.\n\nStaying active in this global community means our patients benefit from techniques and evidence still years away from becoming standard practice elsewhere — while our own experience, in turn, contributes to the field as a whole.",
    ar: "إن تقديم الأبحاث في المؤتمرات الدولية لا يتعلق بالمكانة لذاتها - بل هو الطريقة التي تُختبر بها التقنيات الجراحية أمام جمهور عالمي من الأقران الذين سيطرحون الأسئلة الصعبة التي قد لا يفكر فريقنا في طرحها. فكل سلسلة حالات ومجموعة بيانات نتائج تُعرض على تلك المنصة تعود أكثر صقلاً بعد أن خضعت للتحدي.\n\nتُعد هذه التجمعات أيضاً المكان الذي تتشكل فيه الجيل القادم من الابتكارات في جراحة الكبد والصفراء، قبل وقت طويل من ظهورها في المجلات العلمية أو الإرشادات السريرية. غالباً ما تؤدي المحادثات في أروقة المؤتمرات حول حالة صعبة أو تقنية تصوير جديدة إلى تغييرات مباشرة في كيفية تعاملنا مع المرضى في بلادنا.\n\nإن البقاء نشطاً في هذا المجتمع العالمي يعني أن مرضانا يستفيدون من تقنيات وأدلة لا تزال تفصلها سنوات عن أن تصبح ممارسة معيارية في أماكن أخرى - بينما تساهم خبرتنا في المقابل في هذا المجال ككل.",
    fr: "Présenter lors de conférences internationales n'est pas une question de prestige en soi — c'est ainsi que les techniques chirurgicales sont mises à l'épreuve devant un public mondial de pairs qui poseront les questions difficiles que notre propre équipe n'aurait peut-être pas pensé à poser. Chaque série de cas et ensemble de données de résultats présenté sur cette scène en ressort plus affiné pour avoir été remis en question.\n\nCes rassemblements sont aussi le lieu où se dessine la prochaine génération d'innovations en chirurgie hépatobiliaire, bien avant qu'elle n'apparaisse dans les revues ou les recommandations cliniques. Les conversations dans les couloirs des conférences autour d'un cas difficile ou d'une nouvelle technique d'imagerie mènent souvent directement à des changements dans notre façon d'aborder les patients une fois de retour.\n\nRester actif au sein de cette communauté mondiale signifie que nos patients bénéficient de techniques et de données probantes qui mettront encore des années à devenir la pratique standard ailleurs — tandis que notre propre expérience, en retour, contribue à faire progresser la discipline dans son ensemble.",
  },
  multidisciplinaryCare: {
    en: "No single surgeon manages a complex hepatobiliary case alone. Hepatologists, radiologists, anesthesiologists, transplant coordinators, dietitians, and specialized nursing staff each bring a perspective that shapes the treatment plan long before — and long after — time in the operating room.\n\nA tumor board discussion, for example, brings surgical and non-surgical specialists together to review imaging and pathology as a group, often changing the recommended approach in ways a single specialist working alone would not have considered. The same is true after transplantation, where medication adjustments, nutrition, and physical recovery all need to be coordinated rather than managed in isolation.\n\nThis team-based model takes more time to organize than a single-doctor approach, but it consistently produces better outcomes. When you are treated here, you are never being managed by one opinion — you are being managed by a team that has already debated the best path forward.",
    ar: "لا يتعامل أي جراح بمفرده مع حالة معقدة في جراحة الكبد والصفراء. فأطباء الكبد، وأخصائيو الأشعة، وأطباء التخدير، ومنسقو الزراعة، وأخصائيو التغذية، وطاقم التمريض المتخصص، كل منهم يقدم منظوراً يُشكّل خطة العلاج قبل - وبعد - وقت طويل من دخول غرفة العمليات.\n\nعلى سبيل المثال، يجمع اجتماع مجلس الأورام بين المتخصصين الجراحيين وغير الجراحيين لمراجعة التصوير والفحص المرضي كمجموعة، مما يغيّر غالباً النهج الموصى به بطرق لم يكن ليأخذها بعين الاعتبار متخصص واحد يعمل بمفرده. وينطبق الأمر نفسه بعد الزراعة، حيث تحتاج تعديلات الأدوية والتغذية والتعافي الجسدي جميعها إلى التنسيق بدلاً من إدارتها بشكل منفصل.\n\nيستغرق هذا النموذج القائم على العمل الجماعي وقتاً أطول للتنظيم مقارنة بنهج الطبيب الواحد، لكنه يحقق نتائج أفضل باستمرار. عندما تُعالَج هنا، فأنت لست تحت إدارة رأي واحد فحسب - بل تحت إدارة فريق ناقش بالفعل أفضل طريق للمضي قدماً.",
    fr: "Aucun chirurgien ne gère seul un cas hépatobiliaire complexe. Hépatologues, radiologues, anesthésistes, coordinateurs de transplantation, diététiciens et personnel infirmier spécialisé apportent chacun une perspective qui façonne le plan de traitement bien avant — et bien après — le passage au bloc opératoire.\n\nUne réunion de concertation pluridisciplinaire, par exemple, réunit des spécialistes chirurgicaux et non chirurgicaux pour examiner l'imagerie et l'anatomopathologie en groupe, modifiant souvent l'approche recommandée d'une manière qu'un seul spécialiste travaillant isolément n'aurait pas envisagée. Il en va de même après une transplantation, où les ajustements médicamenteux, la nutrition et la récupération physique doivent tous être coordonnés plutôt que gérés isolément.\n\nCe modèle en équipe demande plus de temps à organiser qu'une approche à médecin unique, mais il produit systématiquement de meilleurs résultats. Lorsque vous êtes traité ici, vous n'êtes jamais suivi par un seul avis — vous êtes pris en charge par une équipe qui a déjà débattu de la meilleure voie à suivre.",
  },
  futureOfHepatology: {
    en: "Hepatology is entering a period of genuine transformation, driven by advances in regenerative medicine, machine-assisted imaging analysis, and a deeper molecular understanding of how liver disease actually progresses. Treatments that once relied purely on managing symptoms are increasingly aimed at intervening earlier, before irreversible damage sets in.\n\nResearch into liver regeneration — building on the organ's own natural capacity to regrow — is opening possibilities that were speculative a decade ago, from bioengineered liver support systems to more precise criteria for who benefits most from a partial versus full transplant. Artificial intelligence is beginning to assist in reading imaging and flagging early markers of disease that a human eye might miss on a first pass.\n\nNone of these advances replace the fundamentals of careful clinical judgment and an honest relationship with each patient, but they sharpen the tools available to support that judgment. The next decade of hepatobiliary care will likely be defined less by any single breakthrough and more by how thoughtfully these tools are integrated into everyday patient care.",
    ar: "يدخل طب الكبد حقبة من التحول الحقيقي، مدفوعاً بالتقدم في الطب التجديدي، وتحليل التصوير بمساعدة الآلة، والفهم الجزيئي الأعمق لكيفية تطور أمراض الكبد فعلياً. فالعلاجات التي كانت تعتمد سابقاً بشكل كامل على إدارة الأعراض، أصبحت تتجه بشكل متزايد نحو التدخل المبكر، قبل حدوث ضرر لا يمكن عكسه.\n\nتفتح الأبحاث في مجال تجديد الكبد - المبنية على القدرة الطبيعية للعضو على إعادة النمو - إمكانيات كانت تخمينية قبل عقد من الزمن، بدءاً من أنظمة دعم الكبد المُصنَّعة حيوياً وصولاً إلى معايير أكثر دقة لتحديد من يستفيد أكثر من زراعة جزئية مقابل زراعة كاملة. وقد بدأ الذكاء الاصطناعي بالمساعدة في قراءة التصوير وتحديد العلامات المبكرة للمرض التي قد تفوتها العين البشرية في القراءة الأولى.\n\nلا شيء من هذه التطورات يحل محل أساسيات الحكم السريري الدقيق والعلاقة الصادقة مع كل مريض، لكنها تصقل الأدوات المتاحة لدعم ذلك الحكم. من المرجح أن يُحدَّد العقد القادم من رعاية الكبد والصفراء بشكل أقل من خلال أي اختراق فردي، وبشكل أكبر من خلال مدى التفكير المتأني في دمج هذه الأدوات ضمن الرعاية اليومية للمرضى.",
    fr: "L'hépatologie entre dans une période de véritable transformation, portée par les avancées en médecine régénérative, l'analyse d'imagerie assistée par ordinateur et une compréhension moléculaire plus fine de la progression réelle des maladies du foie. Les traitements qui reposaient autrefois uniquement sur la gestion des symptômes visent de plus en plus une intervention plus précoce, avant l'apparition de dommages irréversibles.\n\nLa recherche sur la régénération hépatique — s'appuyant sur la capacité naturelle de l'organe à se régénérer — ouvre des possibilités qui relevaient de la spéculation il y a dix ans, des systèmes bioartificiels de soutien hépatique à des critères plus précis pour déterminer qui bénéficie le plus d'une transplantation partielle plutôt que totale. L'intelligence artificielle commence à assister la lecture des images et à signaler des marqueurs précoces de maladie qu'un œil humain pourrait manquer lors d'un premier examen.\n\nAucune de ces avancées ne remplace les fondamentaux d'un jugement clinique rigoureux et d'une relation honnête avec chaque patient, mais elles affinent les outils disponibles pour soutenir ce jugement. La prochaine décennie des soins hépatobiliaires sera probablement définie moins par une percée unique que par la manière réfléchie dont ces outils seront intégrés aux soins quotidiens des patients.",
  },
};

export const articlesSections: SectionDef[] = [
  section(
    "hero",
    "Hero",
    { title: "text", subtitle: "text", backgroundImage: "image", exploreArticles: "button", bookAppointment: "button" },
    {
      title: text("articles.hero.title"),
      subtitle: text("articles.hero.subtitle"),
      backgroundImage: image(
        "https://lh3.googleusercontent.com/aida-public/AB6AXuAE4vIseia-EYulnu-dDGDb9RzxgV-4DUqZh_69wCKTi2kofrPP6eQq7wnQQM0CUdONfXn6mumyMQXWfUlbCUBAaI2BoYlHmhRP0IFZPpf4jlesqggbH6hSakYftwp3puvyjU7ojlbssxp-m8InTw8EHyu7WHyk6dWTFa83xTAPDDQI2sNn1i40fSAX--yEHlgqcR1KYHSEeKJhyNw_7BEUv2GWUEgYiIn4QCw6MSypXFPAFEPsUmsg",
        heroBgAlt,
      ),
      exploreArticles: button(text("articles.hero.exploreArticles"), "#articles"),
      bookAppointment: button(text("articles.hero.bookAppointment"), "/contact"),
    },
  ),
  section("intro", "Intro", { title: "text" }, { title: text("articles.intro.title") }),
  section(
    "featured",
    "Featured Article",
    { bgWord: "text", badge: "text", tag: "text", title: "text", desc: "textarea", body: "textarea", ctaLabel: "text", image: "image" },
    {
      bgWord: text("articles.featured.bgWord"),
      badge: text("articles.featured.badge"),
      tag: text("articles.featured.tag"),
      title: text("articles.featured.title"),
      desc: text("articles.featured.desc"),
      body: featuredBody,
      ctaLabel: text("articles.featured.cta"),
      image: image(
        "https://lh3.googleusercontent.com/aida/AP1WRLvfpYDc6FcWRf7-8U3C022k5lqz6X4F33J3wNJWA3d3PJDmSIxDKF8YeLsDNDqENKK24a16X-efDIK0eC7DUEB4q--EjimQ5Kzy8S0-KdKwTBHGN3qI3lYTViUsgMsGfkhC1-qa8tZ259TOEJVmNtmEMrAHIGX1_Tsc99FrRKU1INWaoe-A4GqF3vTM1zfVH1YZ-8p2OZIfphx1Jsb2af_Kn9GdgCT-I_IoOpTWoxZfDC49dp8JH-YTS3k",
        featuredImageAlt,
      ),
    },
  ),
  section(
    "grid",
    "Articles Grid",
    {
      readArticle: "text",
      items: { type: "array", itemSchema: { image: "image", tag: "text", title: "text", body: "textarea" } },
    },
    {
      readArticle: text("common.readArticle"),
      items: Object.keys(ARTICLE_IMG).map((id) => ({
        id,
        image: image(ARTICLE_IMG[id]!, text(`articles.grid.items.${id}.title`)),
        tag: text(`articles.grid.items.${id}.tag`),
        title: text(`articles.grid.items.${id}.title`),
        body: ARTICLE_BODIES[id],
      })),
    },
  ),
  section(
    "cta",
    "Final CTA",
    { label: "text", title: "text", cta: "button", whatsappUs: "button" },
    {
      label: text("articles.cta.label"),
      title: joinText(text("articles.cta.titleLine1"), text("articles.cta.titleLine2")),
      cta: button(text("articles.cta.cta"), "/contact"),
      whatsappUs: button(text("common.whatsappUs"), "https://wa.me/201234567890"),
    },
  ),
];
